### ISSUE TITLE
TODO to v1

### ISSUE THREAD

**Issue by neoddish** [neoddish/rfm-cli#2]
following features required before publishing v1.0.0:

* [ ] support exe shell after create repo
* [ ] create repo by manifest
* [ ] support subrepo
* [ ] support demo/site subrepo
* [ ] better commands
* [ ] support react
* [ ] support webpack
* [ ] support electron
* [ ] lerna project
* [ ] pretty commands

Any suggestions, support and contributions are welcome and appreciated!
